//! Best-fit constant-delay alignment between the reference and the melange output.
//!
//! # What this replaces, and why
//!
//! `melange validate --oversampling {2|4}` builds the melange side with the
//! codegen option the plugin ships with: the emitted code upsamples through a
//! polyphase IIR half-band, solves at the internal rate, and decimates through
//! another. Those filters are allpass — magnitude-flat, all of their response
//! in the phase — so against an unfiltered ngspice reference the comparison is
//! dominated by their delay.
//!
//! The first attempt at handling that (2026-09-22) pushed the ngspice
//! reference through the SAME round trip with the circuit replaced by an
//! identity, so both signals carried the same filters. That is wrong on a
//! single tone, and wrong in a way that misattributes the residual:
//!
//! - The validate stimulus is one sine at `f0`. On a single tone an allpass is
//!   a pure time shift, and a time-invariant circuit maps a delayed input to an
//!   identically delayed output.
//! - In the shipped build the harmonics are GENERATED by the nonlinearity
//!   AFTER the up leg, so harmonic `k` carries `tau_up(f0) + tau_down(k*f0)`.
//! - In a round-tripped reference the harmonics already exist before the
//!   filters, so harmonic `k` carries `tau_up(k*f0) + tau_down(k*f0)`.
//!
//! The down leg therefore cancels exactly and the up leg is billed at harmonic
//! frequencies it never saw. What such a comparison measures is
//! `tau_up(f0) - tau_up(k*f0)`, which is an artifact of the compensation, not
//! a property of the shipped signal path.
//!
//! # What this does instead
//!
//! Compare the shipped output against THE CIRCUIT: an unfiltered ngspice
//! reference, aligned by ONE best-fit constant delay. "Error modulo a constant
//! delay" is exactly the least-squares statement, so the estimator is the
//! least-squares one:
//!
//! - **Least-squares fractional delay** over the graded window: the delay that
//!   minimises the residual sum of squares, evaluated with the same
//!   band-limited interpolator that is then used to apply it. Any other
//!   estimator leaves delay error in the residual and bills it as shape.
//! - A band-limited cross-correlation peak is the same estimator when it is
//!   done fractionally. Parabolic interpolation of the integer-lag peak is
//!   biased and is NOT used: the integer scan here only picks which cycle, and
//!   a continuous minimisation refines inside it.
//! - **Delay only, never gain.** Correlation is gain-blind and a separate
//!   gain-error gate is the thing that catches scale; a fit that also scaled
//!   would absorb the very quantity that gate measures.
//! - **Seeded and bounded.** On a periodic tone the residual is nearly
//!   periodic in the delay with period `1/f0`, and window-edge effects decide
//!   between neighbouring cycles. The search is seeded at the ANALYTIC round
//!   trip delay computed from the filter design and bounded to +/- half a
//!   period of the stimulus. The fitted delay is reported next to the analytic
//!   one: a fit far from analytic is a finding, not something to swallow.
//! - **Applied in every mode, 1x included**, so the 1x/2x/4x rows stay
//!   commensurable. At 1x the analytic seed is zero and the fit lands near
//!   zero.
//! - **Applied by every path, through one entry point.** [`align_reference`]
//!   is the whole method — the `melange validate` CLI and the CI SPICE gate in
//!   `tests/spice_validation.rs` both call it and nothing else. A second way
//!   of lining two signals up would put two incommensurable measurements in
//!   one release, which is the same defect as an unaligned 1x row.
//!
//! # Where the error floor is
//!
//! Applying a fractional delay means filtering, and the interpolator has a
//! finite length, so it has its own small response. It is a 96-tap Kaiser
//! (beta 9) windowed sinc, normalised to unity DC gain; at an integer delay it
//! is exactly a delta (`sinc(k) = 0` for integer `k != 0`), so the 1x path,
//! where the fit lands near zero, is essentially untouched. The
//! worst case is a half-sample shift, whose residual against an
//! analytically-shifted tone is pinned by
//! `interpolator_error_floor_is_far_below_the_measured_residual` below.

use std::f64::consts::PI;

/// Half-length of the fractional-delay kernel, in samples (96 taps total).
const KERNEL_HALF: usize = 48;

/// Kaiser window beta for the fractional-delay kernel.
const KAISER_BETA: f64 = 9.0;

/// Outcome of a constant-delay fit, for reporting alongside the metrics.
#[derive(Debug, Clone, Copy)]
pub struct DelayFit {
    /// The fitted delay, in samples of the reference's rate. Positive means
    /// the melange output LAGS the reference, so the reference is delayed by
    /// this much to line the two up.
    pub delay_samples: f64,
    /// The analytic delay the search was seeded at: the oversampling round
    /// trip's delay at the stimulus frequency, computed from the filter
    /// design. Zero at 1x.
    pub analytic_samples: f64,
    /// Stimulus frequency the seed and the search bound were derived from, Hz.
    pub stimulus_hz: f64,
    /// Half-width of the search interval around the seed, in samples
    /// (half a period of `stimulus_hz`).
    pub bound_samples: f64,
    /// Residual RMS over the fit window with no alignment at all.
    pub residual_rms_unaligned: f64,
    /// Residual RMS over the fit window at the fitted delay.
    pub residual_rms_aligned: f64,
    /// Set when the fit ran into the edge of its search interval — the fitted
    /// delay is then not an interior minimum and should not be trusted as one.
    pub at_search_bound: bool,
}

impl DelayFit {
    /// One-line summary for the report, naming fitted AND analytic delay.
    pub fn note(&self, sample_rate: f64) -> String {
        let mut s = format!(
            "reference delayed by {:.4} samples ({:.1} us) to best-fit the melange output; \
             least-squares fractional delay, seeded at the analytic {:.4} samples \
             (oversampling round trip at {:.1} Hz), searched +/-{:.1} samples",
            self.delay_samples,
            self.delay_samples / sample_rate * 1e6,
            self.analytic_samples,
            self.stimulus_hz,
            self.bound_samples,
        );
        if self.at_search_bound {
            s.push_str(
                " — WARNING: the fit sits at the edge of its search interval, so it is not \
                 an interior minimum; treat the delay, and every metric downstream of it, \
                 as unestablished",
            );
        }
        s
    }
}

/// Modified Bessel function of the first kind, order 0 — for the Kaiser window.
fn bessel_i0(x: f64) -> f64 {
    let half = x / 2.0;
    let mut term = 1.0f64;
    let mut sum = 1.0f64;
    for k in 1..80 {
        let f = half / k as f64;
        term *= f * f;
        sum += term;
        if term < 1e-18 * sum {
            break;
        }
    }
    sum
}

fn sinc(x: f64) -> f64 {
    if x.abs() < 1e-12 {
        1.0
    } else {
        let p = PI * x;
        p.sin() / p
    }
}

/// Kernel taps for a fractional shift of `frac` in `[0, 1)`.
///
/// `y[n] = sum_k taps[k + H] * x[n - i + k]` for `k` in `-H ..= H-1`, where the
/// sample being reconstructed sits at `n - i - frac`. Normalised to unity DC
/// gain so the interpolator cannot introduce a gain error of its own — this
/// fit is a DELAY fit, and a gain slipped in here would be indistinguishable
/// from the circuit's.
fn kernel_taps(frac: f64) -> Vec<f64> {
    let h = KERNEL_HALF as f64;
    let i0_beta = bessel_i0(KAISER_BETA);
    let mut taps = Vec::with_capacity(2 * KERNEL_HALF);
    let mut sum = 0.0;
    for k in -(KERNEL_HALF as isize)..(KERNEL_HALF as isize) {
        let u = frac + k as f64;
        let r = u / h;
        let w = if r.abs() >= 1.0 {
            0.0
        } else {
            bessel_i0(KAISER_BETA * (1.0 - r * r).sqrt()) / i0_beta
        };
        let t = sinc(u) * w;
        sum += t;
        taps.push(t);
    }
    if sum.abs() > 1e-12 {
        for t in taps.iter_mut() {
            *t /= sum;
        }
    }
    taps
}

#[inline]
fn sample_clamped(x: &[f64], idx: isize) -> f64 {
    if x.is_empty() {
        return 0.0;
    }
    let last = x.len() as isize - 1;
    x[idx.clamp(0, last) as usize]
}

/// Delay `signal` by `delay` samples (fractional, may be negative).
///
/// Out-of-range samples are taken as the nearest end sample (constant
/// extension). With a 96-tap kernel that touches at most `KERNEL_HALF`
/// samples at each end; the fit window is trimmed by the same margin so the
/// fit itself never sees an extended sample.
pub fn apply_fractional_delay(signal: &[f64], delay: f64) -> Vec<f64> {
    let i = delay.floor();
    let frac = delay - i;
    let i = i as isize;
    if frac.abs() < 1e-15 {
        // Exact integer shift — no filtering at all.
        return (0..signal.len())
            .map(|n| sample_clamped(signal, n as isize - i))
            .collect();
    }
    let taps = kernel_taps(frac);
    (0..signal.len())
        .map(|n| {
            let base = n as isize - i;
            let mut acc = 0.0;
            for (j, &t) in taps.iter().enumerate() {
                let k = j as isize - KERNEL_HALF as isize;
                acc += t * sample_clamped(signal, base + k);
            }
            acc
        })
        .collect()
}

/// Residual sum of squares between `actual` and `reference` delayed by `delay`,
/// over `start..end` of the actual signal.
fn residual_sumsq(reference: &[f64], actual: &[f64], start: usize, end: usize, delay: f64) -> f64 {
    let i = delay.floor();
    let frac = delay - i;
    let i = i as isize;
    if frac.abs() < 1e-15 {
        return (start..end)
            .map(|n| {
                let e = actual[n] - sample_clamped(reference, n as isize - i);
                e * e
            })
            .sum();
    }
    let taps = kernel_taps(frac);
    (start..end)
        .map(|n| {
            let base = n as isize - i;
            let mut r = 0.0;
            for (j, &t) in taps.iter().enumerate() {
                let k = j as isize - KERNEL_HALF as isize;
                r += t * sample_clamped(reference, base + k);
            }
            let e = actual[n] - r;
            e * e
        })
        .sum()
}

/// Dominant frequency of `signal`, in Hz — used to seed and bound the search.
///
/// Hann-windowed DFT magnitude peak with a parabolic refinement on the
/// log-magnitude. The refinement is fine HERE: this estimates the STIMULUS
/// frequency, which only sets the seed's evaluation point and the search
/// half-width. It is not the delay estimator, where interpolating an integer
/// peak would be biased.
pub fn dominant_frequency(signal: &[f64], sample_rate: f64) -> Option<f64> {
    let n = signal.len();
    if n < 16 || sample_rate <= 0.0 {
        return None;
    }
    let mean = signal.iter().sum::<f64>() / n as f64;
    let mut planner = rustfft::FftPlanner::new();
    let fft = planner.plan_fft_forward(n);
    let mut buf: Vec<rustfft::num_complex::Complex<f64>> = signal
        .iter()
        .enumerate()
        .map(|(i, &x)| {
            let w = 0.5 - 0.5 * (2.0 * PI * i as f64 / n as f64).cos();
            rustfft::num_complex::Complex::new((x - mean) * w, 0.0)
        })
        .collect();
    fft.process(&mut buf);

    let half = n / 2;
    let mag: Vec<f64> = buf[..half].iter().map(|c| c.norm()).collect();
    // Skip the first few bins: the Hann-windowed residue of a removed DC
    // offset, and any sub-audio drift, are not the stimulus.
    let lo = 2usize;
    let (mut peak, mut peak_mag) = (lo, 0.0);
    for (k, &m) in mag.iter().enumerate().take(half).skip(lo) {
        if m > peak_mag {
            peak_mag = m;
            peak = k;
        }
    }
    if peak_mag <= 0.0 {
        return None;
    }
    let mut bin = peak as f64;
    if peak > 0 && peak + 1 < half {
        let (a, b, c) = (
            mag[peak - 1].max(1e-300).ln(),
            mag[peak].max(1e-300).ln(),
            mag[peak + 1].max(1e-300).ln(),
        );
        let denom = a - 2.0 * b + c;
        if denom.abs() > 1e-12 {
            let d = 0.5 * (a - c) / denom;
            if d.abs() < 1.0 {
                bin += d;
            }
        }
    }
    Some(bin * sample_rate / n as f64)
}

/// Fit ONE constant delay that best aligns `reference` to `actual`.
///
/// `window` is the half-open sample range the metrics will be graded over;
/// the fit is done on that range trimmed by the interpolator's half-length at
/// each end so no fitted sample depends on the constant extension.
///
/// `analytic_samples` seeds the search (the oversampling round trip's delay at
/// the stimulus frequency — zero at 1x) and `stimulus_hz` sets the search
/// half-width to half a period.
pub fn fit_constant_delay(
    reference: &[f64],
    actual: &[f64],
    window: std::ops::Range<usize>,
    analytic_samples: f64,
    stimulus_hz: f64,
    sample_rate: f64,
) -> DelayFit {
    let bound = if stimulus_hz > 0.0 {
        0.5 * sample_rate / stimulus_hz
    } else {
        0.5 * sample_rate / 1000.0
    };

    let guard = KERNEL_HALF;
    let n = reference.len().min(actual.len());
    let mut start = window.start.saturating_add(guard);
    let mut end = window.end.min(n).saturating_sub(guard);
    if end <= start {
        // Window too short for the guard — fall back to the raw window rather
        // than refusing to align at all; the constant extension then touches at
        // most the kernel's tail.
        start = window.start;
        end = window.end.min(n);
    }

    let unaligned = |d: f64| {
        let len = (end - start).max(1) as f64;
        (residual_sumsq(reference, actual, start, end, d) / len).sqrt()
    };

    if end <= start {
        return DelayFit {
            delay_samples: 0.0,
            analytic_samples,
            stimulus_hz,
            bound_samples: bound,
            residual_rms_unaligned: f64::NAN,
            residual_rms_aligned: f64::NAN,
            at_search_bound: false,
        };
    }

    let lo = analytic_samples - bound;
    let hi = analytic_samples + bound;

    // Coarse pass: integer lags only, which are EXACT shifts (no interpolation
    // at all). This picks which cycle the minimum lives in; it is not itself
    // the estimate, so no interpolation of this peak takes place.
    let first = lo.ceil() as isize;
    let last = hi.floor() as isize;
    let mut best_d = analytic_samples;
    let mut best_e = residual_sumsq(reference, actual, start, end, analytic_samples);
    for k in first..=last {
        let e = residual_sumsq(reference, actual, start, end, k as f64);
        if e < best_e {
            best_e = e;
            best_d = k as f64;
        }
    }

    // Fine pass: golden-section minimisation of the SAME least-squares
    // objective over the sample either side of the coarse winner, so the
    // reported residual is the one being minimised.
    let mut a = (best_d - 1.0).max(lo);
    let mut b = (best_d + 1.0).min(hi);
    const PHI_INV: f64 = 0.618_033_988_749_894_9;
    let mut c = b - PHI_INV * (b - a);
    let mut d = a + PHI_INV * (b - a);
    let mut fc = residual_sumsq(reference, actual, start, end, c);
    let mut fd = residual_sumsq(reference, actual, start, end, d);
    while (b - a).abs() > 1e-5 {
        if fc < fd {
            b = d;
            d = c;
            fd = fc;
            c = b - PHI_INV * (b - a);
            fc = residual_sumsq(reference, actual, start, end, c);
        } else {
            a = c;
            c = d;
            fc = fd;
            d = a + PHI_INV * (b - a);
            fd = residual_sumsq(reference, actual, start, end, d);
        }
    }
    let fitted = 0.5 * (a + b);
    let fitted_e = residual_sumsq(reference, actual, start, end, fitted);
    let (fitted, fitted_e) = if fitted_e <= best_e {
        (fitted, fitted_e)
    } else {
        (best_d, best_e)
    };

    let len = (end - start) as f64;
    DelayFit {
        delay_samples: fitted,
        analytic_samples,
        stimulus_hz,
        bound_samples: bound,
        residual_rms_unaligned: unaligned(0.0),
        residual_rms_aligned: (fitted_e / len).sqrt(),
        // "Ran into the edge", stated precisely: the minimiser ended ON an
        // endpoint of the search interval, so the true minimum is outside it
        // and this delay is a boundary value, not a fit.
        at_search_bound: (fitted - lo).abs() < 1e-3 || (fitted - hi).abs() < 1e-3,
    }
}

/// Everything the validation pipeline knows that the delay fit needs.
///
/// A struct rather than seven positional arguments: all but two fields are a
/// rate or a signal, and swapping a pair of them would still produce a number
/// that looks plausible.
#[derive(Debug, Clone, Copy)]
pub struct AlignmentRequest<'a> {
    /// Reference samples, already DC-blocked, at `reference_rate`.
    pub reference: &'a [f64],
    /// The melange output the reference is being lined up with, at
    /// `actual_rate`.
    pub actual: &'a [f64],
    /// The drive, at `actual_rate`. Its fundamental seeds the search bound;
    /// the stimulus is read from the INPUT rather than the output so a
    /// heavily-distorting circuit cannot move the bound.
    pub input_signal: &'a [f64],
    /// Sample rate of `reference`, Hz.
    pub reference_rate: f64,
    /// Sample rate of `actual` and `input_signal`, Hz.
    pub actual_rate: f64,
    /// Codegen oversampling factor the melange side was BUILT with (1, 2 or
    /// 4). Sets the analytic seed; 1 seeds at zero.
    pub oversampling: usize,
    /// Settle window the metrics will be graded over, in seconds. The fit is
    /// done on the graded window so it minimises the residual that is then
    /// reported, rather than a different one.
    pub settle_time_s: f64,
}

/// Align a reference to a melange output: THE single comparison method.
///
/// Every path that grades melange against ngspice — `melange validate` and the
/// CI SPICE gate in `tests/spice_validation.rs` alike — goes through here, so
/// their numbers mean the same thing and stay commensurable. Two paths that
/// each did their own thing would ship one release with two measurements.
///
/// This lives beside the estimator rather than inside `compare_signals`
/// because it needs two things the metric engine cannot see: the oversampling
/// factor the melange side was BUILT with (which sets the analytic seed) and
/// the stimulus that drove the run (which sets the search bound).
/// `compare_signals` is handed two signals and would have to guess both — and
/// it is also used on short synthetic pairs, where fitting a delay is
/// meaningless.
///
/// Call it AFTER the DC blocker, so the blocker still sees the reference's own
/// first sample as its seed.
///
/// Returns the delayed reference — at `reference_rate`, same length, ready for
/// `compare_signals` — and the fit, whose [`DelayFit::note`] belongs on the
/// report: a fitted delay far from the analytic one is a finding.
pub fn align_reference(req: AlignmentRequest<'_>) -> (Vec<f64>, DelayFit) {
    // The fit needs both signals on one clock. Resampling is done with the
    // SAME resampler `compare_signals` applies before it grades anything, so
    // the fit sees the samples the metrics will.
    let actual_at_ref_rate: Vec<f64> =
        if (req.reference_rate - req.actual_rate).abs() > f64::EPSILON {
            crate::comparison::Signal::new(req.actual.to_vec(), req.actual_rate, "fit")
                .resample(req.reference_rate)
                .samples
        } else {
            req.actual.to_vec()
        };

    // The window the metrics will be graded over, so the fit minimises the
    // residual that actually gets reported.
    let graded_len = req.reference.len().min(actual_at_ref_rate.len());
    let graded_start = if req.settle_time_s > 0.0 {
        ((req.settle_time_s * req.reference_rate).round() as usize).min(graded_len)
    } else {
        0
    };

    // Seed: the analytic delay of the oversampling round trip at the stimulus
    // frequency, from the filter design. Zero at 1x.
    //
    // The round trip is clocked at MELANGE's host rate, so it is measured
    // there and then expressed in reference-rate samples — the units the fit
    // works in. The two rates are equal on every deck with `.OPTIONS INTERP`,
    // which is every shipped deck; the conversion is here so that stops being
    // a silent assumption.
    let stimulus_hz = dominant_frequency(req.input_signal, req.actual_rate).unwrap_or(1000.0);
    let analytic = crate::oversampling_round_trip_group_delay_samples(
        req.oversampling,
        req.actual_rate,
        stimulus_hz,
    ) * (req.reference_rate / req.actual_rate);

    let fit = fit_constant_delay(
        req.reference,
        &actual_at_ref_rate,
        graded_start..graded_len,
        analytic,
        stimulus_hz,
        req.reference_rate,
    );
    let aligned = apply_fractional_delay(req.reference, fit.delay_samples);
    (aligned, fit)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tone(n: usize, freq: f64, sr: f64, phase: f64) -> Vec<f64> {
        (0..n)
            .map(|i| (2.0 * PI * freq * i as f64 / sr + phase).sin())
            .collect()
    }

    #[test]
    fn integer_delay_is_an_exact_shift() {
        let x = tone(512, 1000.0, 48_000.0, 0.0);
        let y = apply_fractional_delay(&x, 3.0);
        for n in 3..512 {
            assert!((y[n] - x[n - 3]).abs() < 1e-15, "n={n}");
        }
    }

    #[test]
    fn zero_delay_is_the_identity() {
        let x = tone(512, 1000.0, 48_000.0, 0.3);
        let y = apply_fractional_delay(&x, 0.0);
        assert_eq!(x, y);
    }

    /// The interpolator's own error, at its worst case (a half-sample shift),
    /// measured against the analytic answer for tones across the band. This is
    /// the floor under every aligned number the harness reports, so it is
    /// pinned rather than assumed: it has to sit far below the residuals being
    /// measured (order 1e-3 relative on `tube_screamer_u`).
    ///
    /// Measured 2026-09-23 on a unit-amplitude tone: 7.9e-7 at 100 Hz,
    /// 7.1e-9 at 1 kHz, 1.8e-7 at 5 kHz, 1.7e-6 at 15 kHz — three orders
    /// below the residuals, and the bound below is deliberately looser than
    /// the measurement so it pins the ORDER, not the last digit.
    #[test]
    fn interpolator_error_floor_is_far_below_the_measured_residual() {
        let sr = 48_000.0;
        let n = 4096;
        // Up to 15 kHz: the band where a 1 kHz stimulus' harmonics carry
        // anything. The kernel's transition sits at Nyquist, so error grows
        // as the content approaches 24 kHz — reported here, not hidden.
        for &f in &[100.0f64, 1_000.0, 3_000.0, 5_000.0, 10_000.0, 15_000.0] {
            let x = tone(n, f, sr, 0.0);
            let y = apply_fractional_delay(&x, 0.5);
            let w = 2.0 * PI * f / sr;
            let exact: Vec<f64> = (0..n).map(|i| (w * (i as f64 - 0.5)).sin()).collect();
            let lo = KERNEL_HALF;
            let hi = n - KERNEL_HALF;
            let err = ((lo..hi).map(|i| (y[i] - exact[i]).powi(2)).sum::<f64>() / (hi - lo) as f64)
                .sqrt();
            assert!(
                err < 1e-5,
                "half-sample interpolation error at {f} Hz is {err:e}, \
                 too close to the residuals this harness reports"
            );
        }
    }

    #[test]
    fn fit_recovers_a_known_fractional_delay() {
        let sr = 48_000.0;
        let n = 4096;
        let refr = tone(n, 1000.0, sr, 0.0);
        for &true_d in &[0.0f64, 0.37, 1.5, -0.8, 2.25] {
            let act = apply_fractional_delay(&refr, true_d);
            let fit = fit_constant_delay(&refr, &act, 0..n, 0.0, 1000.0, sr);
            assert!(
                (fit.delay_samples - true_d).abs() < 2e-3,
                "fitted {} vs true {true_d}",
                fit.delay_samples
            );
            assert!(!fit.at_search_bound);
        }
    }

    /// A fit that ends ON an endpoint of its search interval is a boundary
    /// value, not a minimum, and the report has to SAY so rather than present
    /// it as an answer.
    ///
    /// The signal is a 20 Hz tone (period 2400 samples) delayed by 40 with the
    /// search bounded to +/-24: the residual is still falling at the edge, so
    /// the minimiser is pinned there. A tone AT the stimulus frequency could
    /// not show this — a delay past the bound is then genuinely
    /// indistinguishable from one inside it, which is why the bound exists.
    #[test]
    fn a_fit_stuck_on_its_search_bound_says_so() {
        let sr = 48_000.0;
        let n = 8192;
        let slow = tone(n, 20.0, sr, 0.0);
        let act = apply_fractional_delay(&slow, 40.0);
        let fit = fit_constant_delay(&slow, &act, 0..n, 0.0, 1000.0, sr);
        assert!(
            fit.at_search_bound,
            "fit landed at {} with bound {} and did not flag it",
            fit.delay_samples, fit.bound_samples
        );
        assert!(fit.note(sr).contains("WARNING"));
    }

    /// The fit must not absorb a gain error: a reference scaled by 1.05 still
    /// fits the same delay, and the residual stays behind for the gate to see.
    #[test]
    fn fit_is_delay_only_and_leaves_gain_error_in_the_residual() {
        let sr = 48_000.0;
        let n = 4096;
        let refr = tone(n, 1000.0, sr, 0.0);
        let act: Vec<f64> = apply_fractional_delay(&refr, 1.25)
            .iter()
            .map(|v| v * 1.05)
            .collect();
        let fit = fit_constant_delay(&refr, &act, 0..n, 0.0, 1000.0, sr);
        assert!(
            (fit.delay_samples - 1.25).abs() < 5e-3,
            "gain moved the delay fit: {}",
            fit.delay_samples
        );
        // 5% of an RMS-0.707 tone survives the alignment.
        assert!(
            fit.residual_rms_aligned > 0.03,
            "the fit swallowed the gain error: residual {}",
            fit.residual_rms_aligned
        );
    }

    #[test]
    fn search_is_bounded_to_half_a_period_and_says_when_it_hits_the_edge() {
        let sr = 48_000.0;
        let n = 4096;
        let refr = tone(n, 1000.0, sr, 0.0);
        // A full period of delay is outside +/- half a period of the seed, so
        // the fit cannot walk to it silently.
        let act = apply_fractional_delay(&refr, 48.0);
        let fit = fit_constant_delay(&refr, &act, 0..n, 0.0, 1000.0, sr);
        assert!(fit.delay_samples.abs() <= fit.bound_samples + 1e-9);
        assert!((fit.bound_samples - 24.0).abs() < 1e-9);
    }

    #[test]
    fn dominant_frequency_finds_the_stimulus() {
        let sr = 48_000.0;
        let x = tone(4096, 1000.0, sr, 0.0);
        let f = dominant_frequency(&x, sr).expect("frequency");
        assert!((f - 1000.0).abs() < 5.0, "got {f}");
    }
}
