//! Golden reference tests: codegen output vs recorded reference output.
//!
//! These tests verify that the codegen pipeline produces output matching
//! recorded reference waveforms within tolerance.
//!
//! Reference provenance is mixed and each file's `generator` field is
//! authoritative:
//! - most goldens were recorded by `record_golden_refs.rs` from the
//!   (since deleted) runtime solver;
//! - `opamp_inverting_sine_1k.json`, `opamp_noninverting_sine_1k.json`
//!   and `triode_cc_small_sine_500hz.json` hold NGSPICE output
//!   (review-round-2 H1 fix: goldens re-recorded from melange's own
//!   codegen cannot arbitrate a solver-math dispute). They are
//!   regenerated by `tests/golden/ngspice_ref/regen_ngspice_goldens.py`
//!   from the deck templates in the same directory — never from melange.
//! - `triode_cc_sine_500hz.json` (0.5 V drive, 742/960 samples at the
//!   ±10 V output clamp) intentionally remains a codegen self-recording:
//!   the clamp is a melange codegen feature with no ngspice counterpart,
//!   so this golden gates the clamp and sample-level drift only. The
//!   tube TRANSFER CURVE is gated by the ngspice-referenced small-signal
//!   companion below.

mod support;

use melange_solver::codegen::CodegenConfig;

const SR: f64 = 48000.0;

// ── Circuit definitions (same as record_golden_refs.rs) ────────────────

const RC_LOWPASS: &str = "\
RC Lowpass
R1 in out 1k
C1 out 0 1u
";

const RC_HIGHPASS: &str = "\
RC Highpass
C1 in out 1u
R1 out 0 1k
";

const DIODE_CLIPPER: &str = "\
Diode Clipper
R1 in out 1k
D1 out 0 DMOD
D2 0 out DMOD
C1 out 0 1u
.model DMOD D(IS=2.52e-9 N=1.752)
";

const BJT_CE: &str = "\
BJT Common Emitter
Cin in base 10u
R1 vcc base 100k
R2 base 0 22k
Q1 coll base emit MYBJTCE
Rc vcc coll 4.7k
Re emit 0 1k
Ce emit 0 100u
Cout coll out 10u
Rload out 0 100k
Vcc vcc 0 DC 12
.model MYBJTCE NPN(IS=1e-14 BF=200 BR=3)
";

const JFET_CS: &str = "\
JFET Common Source
Cin in gate 10u
Rg gate 0 1Meg
J1 drain gate source J2N5457
Rd vdd drain 2.2k
Rs source 0 1k
Cs source 0 100u
Cout drain out 10u
Rload out 0 100k
Vdd vdd 0 DC 12
.model J2N5457 NJ(VTO=-2.0 IDSS=5e-3 LAMBDA=0.001)
";

const MOSFET_CS: &str = "\
MOSFET Common Source
Cin in gate 10u
R1 vdd gate 47k
R2 gate 0 100k
M1 drain gate source 0 NMOD
Rd vdd drain 1k
Rs source 0 100
Cs source 0 100u
Cout drain out 10u
Rload out 0 100k
Vdd vdd 0 DC 5
.model NMOD NM(VTO=2.0 KP=0.1 LAMBDA=0.01)
";

const TRIODE_CC: &str = "\
12AX7 Common Cathode
Rin in 0 1Meg
Cin in grid 100n
Rg grid 0 1Meg
T1 grid plate cathode 12AX7
Rk cathode 0 1.5k
Ck cathode 0 25u
Rp vcc plate 100k
Cout plate out 100n
Rout out 0 1Meg
Vcc vcc 0 DC 250
.model 12AX7 TUBE(MU=100 EX=1.4 KG1=1060 KP=600 KVB=300)
";

const OPAMP_INVERTING: &str = "\
Inverting Amplifier
R1 in vminus 1k
R2 vminus out 10k
U1 0 vminus out OPA
.model OPA OA(AOL=200000 ROUT=1)
";

const OPAMP_NONINVERTING: &str = "\
Non-Inverting Amplifier
R1 0 vminus 1k
R2 vminus out 10k
U1 in vminus out OPA
.model OPA OA(AOL=200000 ROUT=1)
";

// ── Helpers ────────────────────────────────────────────────────────────

fn config(spice: &str) -> CodegenConfig {
    support::config_for_spice(spice, SR)
}

// ── Linear circuit golden ref tests ────────────────────────────────────

#[test]
fn golden_rc_lowpass_step() {
    let c = config(RC_LOWPASS);
    let circuit = support::build_circuit(RC_LOWPASS, &c, "g_rc_step");
    let output = support::run_step(&circuit, 1.0, 300, SR);
    support::assert_matches_golden(&output, "rc_lowpass_step.json", 1e-10);
}

#[test]
fn golden_rc_lowpass_sine_1k() {
    let c = config(RC_LOWPASS);
    let circuit = support::build_circuit(RC_LOWPASS, &c, "g_rc_sine");
    let output = support::run_sine(&circuit, 1000.0, 0.5, 480, SR);
    support::assert_matches_golden(&output, "rc_lowpass_sine_1k.json", 1e-10);
}

#[test]
fn golden_rc_highpass_sine_1k() {
    let c = config(RC_HIGHPASS);
    let circuit = support::build_circuit(RC_HIGHPASS, &c, "g_rc_hp");
    let output = support::run_sine(&circuit, 1000.0, 0.5, 480, SR);
    support::assert_matches_golden(&output, "rc_highpass_sine_1k.json", 1e-10);
}

/// Reference: ngspice-42 (independent), G-element VCCS twin with correct
/// polarity (`G1 out 0 vminus 0 200000`). Regenerate via
/// `tests/golden/ngspice_ref/regen_ngspice_goldens.py`.
///
/// Tolerance: measured 2026-07-21 max |melange − ngspice| = 1.12e-8 V
/// (memoryless linear circuit — PWL/INTERP interpolation is exact, so the
/// two engines agree to solver round-off). 1e-6 = 89× measured margin.
#[test]
fn golden_opamp_inverting_sine_1k() {
    let c = config(OPAMP_INVERTING);
    let circuit = support::build_circuit(OPAMP_INVERTING, &c, "g_opamp_inv");
    let output = support::run_sine(&circuit, 1000.0, 0.1, 480, SR);
    support::assert_matches_golden(&output, "opamp_inverting_sine_1k.json", 1e-6);
}

/// Reference: ngspice-42 (independent), G-element VCCS twin with correct
/// polarity (`G1 out 0 vminus in 200000` — injects Gm·(V(in) − V(vminus))
/// INTO out). No noninverting reference deck existed before 2026-07-21;
/// see `tests/golden/ngspice_ref/opamp_noninverting_ref.cir.tmpl`.
///
/// Tolerance: measured 2026-07-21 max |melange − ngspice| = 1.27e-8 V.
/// 1e-6 = 79× measured margin.
#[test]
fn golden_opamp_noninverting_sine_1k() {
    let c = config(OPAMP_NONINVERTING);
    let circuit = support::build_circuit(OPAMP_NONINVERTING, &c, "g_opamp_ni");
    let output = support::run_sine(&circuit, 1000.0, 0.1, 480, SR);
    support::assert_matches_golden(&output, "opamp_noninverting_sine_1k.json", 1e-6);
}

// ── Nonlinear circuit golden ref tests ─────────────────────────────────

#[test]
fn golden_diode_clipper_sine_500hz() {
    let c = config(DIODE_CLIPPER);
    let circuit = support::build_circuit(DIODE_CLIPPER, &c, "g_diode");
    let output = support::run_sine(&circuit, 500.0, 1.0, 960, SR);
    support::assert_matches_golden(&output, "diode_clipper_sine_500hz.json", 1e-6);
}

#[test]
fn golden_bjt_ce_sine_500hz() {
    let c = config(BJT_CE);
    let circuit = support::build_circuit(BJT_CE, &c, "g_bjt");
    let output = support::run_sine(&circuit, 500.0, 0.05, 960, SR);
    support::assert_matches_golden(&output, "bjt_ce_sine_500hz.json", 1e-4);
}

#[test]
fn golden_jfet_cs_sine_500hz() {
    let c = config(JFET_CS);
    let circuit = support::build_circuit(JFET_CS, &c, "g_jfet");
    let output = support::run_sine(&circuit, 500.0, 0.1, 960, SR);
    support::assert_matches_golden(&output, "jfet_cs_sine_500hz.json", 1e-4);
}

#[test]
fn golden_mosfet_cs_sine_500hz() {
    let c = config(MOSFET_CS);
    let circuit = support::build_circuit(MOSFET_CS, &c, "g_mosfet");
    let output = support::run_sine(&circuit, 500.0, 0.1, 960, SR);
    support::assert_matches_golden(&output, "mosfet_cs_sine_500hz.json", 1e-4);
}

/// Clamp gate: 0.5 V drive into a gain ≈ −59 stage → ~30 V pre-clamp swing,
/// 742/960 samples pinned at the ±10 V codegen output clamp. This golden is
/// a codegen SELF-recording (the clamp has no ngspice counterpart) and gates
/// the clamp + sample-level drift only — see
/// `golden_triode_cc_small_sine_500hz` for the ngspice-referenced
/// transfer-curve gate (review-round-2 H3).
#[test]
fn golden_triode_cc_sine_500hz() {
    let c = config(TRIODE_CC);
    let circuit = support::build_circuit(TRIODE_CC, &c, "g_triode");
    let output = support::run_sine(&circuit, 500.0, 0.5, 960, SR);
    support::assert_matches_golden(&output, "triode_cc_sine_500hz.json", 2e-4);
}

/// Small-signal companion (review-round-2 H3): 40 mV drive keeps the whole
/// waveform inside the ±10 V rails (peak 2.38 V), so every sample carries
/// plate-current information and the Koren transfer curve is actually gated.
///
/// Reference: ngspice-42 B-source Koren twin (independent of melange) —
/// `Ip = 2·pwr(uramp(E1),EX)/KG1` — regenerated by
/// `tests/golden/ngspice_ref/regen_ngspice_goldens.py`. DC OP cross-check:
/// plate 170.1017 V / cathode 1.1985 V on BOTH engines (4+ decimals).
///
/// Tolerance: measured 2026-07-21 max |melange − ngspice| = 2.54e-3 V
/// (0.105% normalized rms). 6e-3 = 2.4× measured margin. A ×2-class
/// plate-current error (the July 2026 Koren dispute) moves the peak by
/// >1 V and fails by >400×.
#[test]
fn golden_triode_cc_small_sine_500hz() {
    let c = config(TRIODE_CC);
    let circuit = support::build_circuit(TRIODE_CC, &c, "g_triode_small");
    let output = support::run_sine(&circuit, 500.0, 0.04, 960, SR);
    support::assert_matches_golden(&output, "triode_cc_small_sine_500hz.json", 6e-3);

    // Pinned stage gain (review-round-2 H4 tripwire, triode family).
    // Settled-window RMS gain: samples 480..960 = exactly 5 cycles of 500 Hz.
    // Measured 2026-07-21: melange +35.3573 dB, ngspice B-source reference
    // +35.3563 dB (Δ = 0.0010 dB). ±0.2 dB gate = 200× the engine delta;
    // a ×2 plate-current error moves this by ≈ 6 dB.
    //
    // RE-PIN PROTOCOL: if this literal ever needs to move, produce the
    // OOMOX_CONTRACT.md §7 downstream impact list FIRST (per-stage deltas
    // multiply through cascades: series-of-tubes ×64, uniquorn ×16) and
    // re-derive the ngspice reference — do not re-pin from melange output.
    let settled = &output[480..];
    let out_rms = (settled.iter().map(|v| v * v).sum::<f64>() / settled.len() as f64).sqrt();
    let in_rms = 0.04 / std::f64::consts::SQRT_2;
    let gain_db = 20.0 * (out_rms / in_rms).log10();
    assert!(
        (gain_db - 35.3573).abs() < 0.2,
        "triode CC stage gain drifted: measured {gain_db:.4} dB vs pinned +35.3573 dB \
         (ngspice B-source reference: +35.3563 dB, measured 2026-07-21)"
    );
}

/// Re-records the triode golden reference from the current codegen output.
/// `record_golden` refuses to overwrite — delete the JSON first, run with
/// `-- --include-ignored record_triode`, then commit the regenerated file.
///
/// History: the original recording came from the (since deleted) runtime
/// CircuitSolver via record_golden_refs.rs. It was re-recorded 2026-07-18
/// after restoring the missing ×2 in the Koren triode plate-current
/// equation (Ip = 2·E1^EX/KG1); the old file asserted the halved currents.
#[test]
#[ignore]
fn record_triode_cc_sine_500hz_codegen() {
    let c = config(TRIODE_CC);
    let circuit = support::build_circuit(TRIODE_CC, &c, "g_triode_rec");
    let output = support::run_sine(&circuit, 500.0, 0.5, 960, SR);
    support::record_golden(
        "triode_cc_sine_500hz.json",
        "triode_cc_sine_500hz",
        TRIODE_CC,
        &output,
        1e-4,
        "codegen_dk (2026-07-18, Koren x2 fix)",
    );
}
